name: Build & Release on Npmjs.com
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        id: setup_node
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Deploy to Npmjs
        id: deploy_npmjs
        run: npm publish . --scope=@letsrokk --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}